# Generated by Django 3.2.5 on 2021-07-21 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210721_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='product name')),
                ('short_desk', models.CharField(blank=True, max_length=256, verbose_name='short dicription')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('description', models.CharField(blank=True, max_length=256, verbose_name='dicription')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price')),
                ('quanity', models.PositiveIntegerField(default=0, verbose_name='quanity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productcategory', verbose_name='category')),
            ],
        ),
    ]
